clear
echo "Welcome to the InspIRCd Configuration program!"
echo ""
echo "*** If you are unsure of any of these values, leave it blank for    ***"
echo "*** standard settings that will work, and your server will run      ***"
echo "*** using them. If you are running this server as part of a         ***"
echo "*** larger network, you must consult with your network admins       ***"
echo "*** for the proper values to use, or server links will be unstable! ***"
echo ""
echo "Press <RETURN> to accept the default for any option, or enter a new value."
echo ""

ME=`pwd`

###############################################################################

TEST=`pwd`
echo "" 
echo "Where do you want to place your configuration files? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   INSTALLPATH=$TEST
else 
   chdir "$cc"
   INSTALLPATH=`pwd`
   chdir "$ME"
fi

INSTALLPATH=$INSTALLPATH/inspircd.conf


###############################################################################

TEST=`pwd`
TEST=$TEST/modules
echo "" 
echo "Where do you want the modules to be stored? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   MODPATH=$TEST
else 
   chdir "$cc"
   MODPATH=`pwd`
   chdir "$ME"
fi

###############################################################################

TEST=1024
echo "" 
echo "Maximum number of clients at any one time? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   MAXCLIENTS=$TEST
else 
   MAXCLIENTS=$cc
fi

###############################################################################

TEST=32
echo "" 
echo "Maximum length of nicknames? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   NICKMAX=$TEST
else 
   NICKMAX=$cc
fi

###############################################################################

TEST=64
echo "" 
echo "Maximum length of a channel name? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   CHANMAX=$TEST
else 
   CHANMAX=$cc
fi

###############################################################################

TEST=20
echo "" 
echo "Maximum number of channels a user may be on? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   MAXCHANS=$TEST
else 
   MAXCHANS=$cc
fi

###############################################################################

TEST=10000
echo "" 
echo "Maximum number of channels on the network (hard limit)? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   MAXCHAN=$TEST
else 
   MAXCHAN=$cc
fi

###############################################################################

TEST=256
echo "" 
echo "Maximum number of channels modes in a channels mode string? ($TEST)" 
read cc 
if [ -z "$cc" ] ; then 
   MAXMODES=$TEST
else 
   MAXMODES=$cc
fi

###############################################################################

clear
echo "Configuration is complete!"
echo ""
echo "Config path:         $INSTALLPATH"
echo "Module path:         $MODPATH"
echo "Max connections:     $MAXCLIENTS"
echo "Max nickname length: $NICKMAX"
echo "Max channel length:  $CHANMAX"
echo "Channel hard limit:  $MAXCHAN"
echo "Max mode length:     $MAXMODES"
echo ""
echo "Writing inspircd_config.h ..."

echo "/* Auto generated by configure, do not modify! */" >inspircd_config.h
echo "" >>inspircd_config.h
echo "#define SYSLOG_FACILITY LOG_DAEMON" >>inspircd_config.h
echo "#define SYSLOG_LEVEL LOG_NOTICE" >>inspircd_config.h
echo "#define CONFIG_FILE \"$INSTALLPATH\"" >>inspircd_config.h
echo "#define MOD_PATH \"$MODPATH\"" >>inspircd_config.h
echo "#define VERSION \"`./version.sh`\"" >>inspircd_config.h
echo "#define MAXCLIENTS $MAXCLIENTS" >>inspircd_config.h
echo "#define NICKMAX $NICKMAX" >>inspircd_config.h
echo "#define CHANMAX $CHANMAX" >>inspircd_config.h
echo "#define MAXCHANS $MAXCHANS" >>inspircd_config.h
echo "#define MAXCHAN $MAXCHAN" >>inspircd_config.h
echo "#define MAXMODES $MAXMODES" >>inspircd_config.h

touch inspircd_config.h
rm -rf *.o

echo "Done!"
echo ""
echo "To build your server with these settings, please type 'make' now."
echo ""
echo "*** Remember to edit your configuration files!!! ***"
echo ""

