/* Auto generated by configure, do not modify! */

#define SYSLOG_FACILITY LOG_DAEMON
#define SYSLOG_LEVEL LOG_NOTICE
#define CONFIG_FILE "/home/brain/inspircd/inspircd.conf"
#define MOD_PATH "/home/brain/inspircd/modules"
#define VERSION "InspIRCd-1.0[Alpha0]"
#define MAXCLIENTS 64
#define NICKMAX 32
#define CHANMAX 64
#define MAXCHANS 20
#define MAXCHAN 10000
#define MAXMODES 256
